# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Instalar Node.js'


- script: |
    npm install
    npm run build
  displayName: 'Instalar dependencias y compilar proyecto'


- script: |
    npm test
  displayName: 'Ejecutar pruebas automáticas'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'vite-build'
    publishLocation: 'Container'
  displayName: 'Publicar artefacto (build de Vite)'


- script: |
    echo "Desplegando aplicación en entorno de pruebas..."
    echo "Despliegue completado correctamente."
  displayName: 'Desplegar aplicación'


- script: |
    echo "Revisando logs del build..."
    echo "Estado del pipeline: OK ✅"
  displayName: 'Monitoreo y validación'
